#!/bin/bash

START=0
STOP=15
STID=0

LONG_OPTIONS="stid,start_beam:,stop_beam:"

OPTIONS=$(getopt -l "$LONG_OPTIONS" -- "$@")

while true; do
    case "$1" in
	--stid)
	    STID=1
	    shift
	    ;;
	--start_beam)
	    START="$2"
	    shift 2
	    ;;
	--stop_beam)
	    STOP="$2"
	    shift 2
	    ;;
	--)
	    shift
	    break
	    ;;
	*) break ;;
    esac
done
	
FILENAME=$1
RADAR=$2
DIR=$3

for bm in $(seq $START $STOP); do
    if [ $STID -eq 0 ]
    then
	   vel_est -b $bm -i $DIR/$FILENAME $RADAR 
    else
	   vel_est -b $bm -i -s $DIR/$FILENAME $RADAR 
    fi	
done



